version: "3"

services:
  app:
    container_name: culture_api
    restart: always
    build: .
    expose:
      - '1234'
    ports:
      - "1234:1234"
    env_file:
      - .env
    command: npm run start:deploy