version: "3"
services:
  app:
    container_name: culture_api
    restart: always
    build: .
    ports:
      - "3001:3001"
    links:
      - mongo
    env_file:
      - .env
    environment: 
      - DB_HOST=mongodb://mongo:27017/culture_db
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
